// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var ApolloLinks = require("reason-apollo/src/ApolloLinks.bs.js");
var ApolloLink = require("apollo-link");
var ReasonApollo = require("reason-apollo/src/ReasonApollo.bs.js");
var ApolloUtilities = require("apollo-utilities");
var ApolloInMemoryCache = require("reason-apollo/src/ApolloInMemoryCache.bs.js");

var graphQLUri = "http://localhost:8080/v1/graphql";

var inMemoryCache = ApolloInMemoryCache.createInMemoryCache(undefined, undefined, /* () */0);

var httpLink = ApolloLinks.createHttpLink(graphQLUri, undefined, undefined, undefined, undefined, undefined, /* () */0);

var webSocketLink = ApolloLinks.webSocketLink("ws://localhost:8080/v1/graphql", true, undefined, /* () */0);

var webSocketHttpLink = ApolloLink.split((function (operation) {
        var operationDefition = ApolloUtilities.getMainDefinition(operation.query);
        if (operationDefition.kind === "OperationDefinition") {
          return operationDefition.operation === "subscription";
        } else {
          return false;
        }
      }), webSocketLink, httpLink);

var client = ReasonApollo.createApolloClient(webSocketHttpLink, inMemoryCache, undefined, undefined, undefined, undefined, /* () */0);

exports.graphQLUri = graphQLUri;
exports.inMemoryCache = inMemoryCache;
exports.httpLink = httpLink;
exports.webSocketLink = webSocketLink;
exports.webSocketHttpLink = webSocketHttpLink;
exports.client = client;
/* inMemoryCache Not a pure module */
