// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Antd = require("antd");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

function PodcastCard(Props) {
  var item = Props.item;
  var setAudioUrl = Props.setAudioUrl;
  var audioUrl = Props.audioUrl;
  var itemAudioUrl = Belt_Option.mapWithDefault(item.enclosure, "", (function (enclosure) {
          return enclosure.url;
        }));
  var isPlaying = itemAudioUrl === audioUrl;
  var author = Belt_Option.mapWithDefault(item.author, null, (function (prim) {
          return prim;
        }));
  var description = Belt_Option.getWithDefault(item.description, "");
  return React.createElement(Antd.Card, {
              children: null
            }, React.createElement("h2", undefined, item.title), React.createElement("i", undefined, author), React.createElement("div", {
                  dangerouslySetInnerHTML: {
                    __html: description
                  }
                }), React.createElement("div", {
                  style: {
                    display: "flex",
                    alignItems: "center"
                  }
                }, isPlaying ? null : React.createElement(Antd.Button, {
                        icon: "caret-right",
                        shape: "circle",
                        type: "primary",
                        onClick: (function (_event) {
                            return Curry._1(setAudioUrl, (function (_currentAudioUrl) {
                                          return itemAudioUrl;
                                        }));
                          })
                      }), React.createElement(Antd.Button, {
                      icon: "heart",
                      shape: "circle",
                      type: "danger",
                      onClick: (function (_event) {
                          console.log("Save to like ");
                          return /* () */0;
                        })
                    })));
}

var make = PodcastCard;

exports.make = make;
/* antd Not a pure module */
