// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var Item = /* module */[];

var Breadcrumb = /* module */[/* Item */Item];

var Button = /* module */[];

var Form = /* module */[];

var Icon = /* module */[];

var Group = /* module */[];

var Password = /* module */[];

var Search = /* module */[];

var TextArea = /* module */[];

var Input = /* module */[
  /* Group */Group,
  /* Password */Password,
  /* Search */Search,
  /* TextArea */TextArea
];

var Header = /* module */[];

var Content = /* module */[];

var Footer = /* module */[];

var Sider = /* module */[];

var Layout = /* module */[
  /* Header */Header,
  /* Content */Content,
  /* Footer */Footer,
  /* Sider */Sider
];

var SubMenu = /* module */[];

var ItemGroup = /* module */[];

var Item$1 = /* module */[];

var Menu = /* module */[
  /* SubMenu */SubMenu,
  /* ItemGroup */ItemGroup,
  /* Item */Item$1
];

var $$Option = /* module */[];

var OptGroup = /* module */[];

var Select = /* module */[
  /* Option */$$Option,
  /* OptGroup */OptGroup
];

var Column = /* module */[];

var ColumnGroup = /* module */[];

var Table = /* module */[
  /* Column */Column,
  /* ColumnGroup */ColumnGroup
];

var Message = /* module */[];

var Popconfirm = /* module */[];

var Card = /* module */[];

exports.Breadcrumb = Breadcrumb;
exports.Button = Button;
exports.Form = Form;
exports.Icon = Icon;
exports.Input = Input;
exports.Layout = Layout;
exports.Menu = Menu;
exports.Select = Select;
exports.Table = Table;
exports.Message = Message;
exports.Popconfirm = Popconfirm;
exports.Card = Card;
/* No side effect */
